### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by dinuand** [rosedu/cdl#1]
Colors used for update:

**main title** and **menu background**: #FF9800
**sections title** and **menu-items hover**: #1277bd
**footer icons and text** and **menu-items**: #212121

![color-test-p74](https://cloud.githubusercontent.com/assets/6827645/6059610/7b8b6faa-ad3c-11e4-82e5-bab5b94315e2.png)

![color-test-p75](https://cloud.githubusercontent.com/assets/6827645/6059615/8b1f57ec-ad3c-11e4-87c6-dd8cdc9d4424.png)

![color-test-p7footer](https://cloud.githubusercontent.com/assets/6827645/6059619/939aac46-ad3c-11e4-94b8-d30427e986b9.png)

**Comment by dinuand** [comment]
I also updated a version with a small change on footer:
**footer social icons** and **footer text** color: #90918D

![color-test-v31](https://cloud.githubusercontent.com/assets/6827645/6084998/c341eee8-ae3e-11e4-9403-1a517cc673f6.png)

**Comment by maria** [comment]
I think we can close it.
