### ISSUE TITLE
Add OG tags for Facebook

### ISSUE THREAD

**Issue by palcu** [rosedu/cdl#14]
# Need

``` gherkin
As a social media freak
I want to share the CDL page
With nice pictures
```

![screen shot 2015-02-09 at 11 58 38](https://cloud.githubusercontent.com/assets/772220/6104086/174574d6-b053-11e4-88ae-ce6fb9cdeb08.png)
# Solution

Add [OG](http://ogp.me/) tags with image, description and title.
## Notes
- Also add them for the big template

**Comment by dinuand** [comment]
Ok, I'll fix that. Thank's. :+1:

**Comment by dinuand** [comment]
How it looks right now:

![og_tags](https://cloud.githubusercontent.com/assets/6827645/6105435/c9df06a0-b05f-11e4-9a15-933928e3f2af.png)

Do you think it's ok or we should put this image instead? [link-to-image](https://raw.githubusercontent.com/rosedu/cdl/gh-pages/assets/images/cdl_logo.png).

**Comment by dinuand** [comment]
@palcu says it's cool, @maria , what's your opinion about that?

**Comment by maria** [comment]
+1
