### ISSUE TITLE
Add references to old CDL editions

### ISSUE THREAD

**Issue by dinuand** [rosedu/cdl#18]
## Need

```
We need in our website to have references to the CDL editions that were organized 
in the past.
```

Now, we have multiple repositories containing the code for each edition and all
are accesible with the prefix _cdl-old.rosedu.org/_. And that's not all. 
For example, if we click on a link in any of those _cdl-old..._ websites, that link will
redirect us to _cdl.rosedu.org..._ and we will receive Error 404, of course.

![cdl-ed](https://cloud.githubusercontent.com/assets/6827645/6156245/2da7b71c-b241-11e4-821e-e833089ef73f.jpg)
## Solution
- Create separate folders for each edition in the current cdl repo [link to repo](https://github.com/rosedu/cdl) and move the code there. _e.g._ A folder called 2014 for the last year edition.
- Eventually make some modifications in the code and name the edition differently, depending on how we decide to name the folder.
- Create a special section in our current edition website and add links to previous editions.

**Comment by dinuand** [comment]
@adasolcan , @calincru , @maria what do you think about that?

**Comment by calincru** [comment]
I think it's a good idea to have links to previous cdl editions, but I'm not sure it is a good idea to move them within the current repo. Maybe we should keep them decoupled and just add links to them.

**Comment by maria** [comment]
> I think it's a good idea to have links to previous cdl editions, but I'm not sure it is a good idea to move them within the current repo. Maybe we should keep them decoupled and just add links to them

OK, but all of those will be `cdl-old`, and we have to update in that repo code base the base URL.

**Comment by dinuand** [comment]
I think the most handy solution would be to create within the current repo separate folders for each previous CDL edition. 

**For example**, for the last year Etti edition, [cdl-old.rosedu.org/2014-etti/](cdl-old.rosedu.org/2014-etti/), we could just create a folder named _2014-etti_, move the code of that edition into the folder and everything should work properly. And so on, for the others editions. 

However, **the problem** that we still need to face if we do so, is with the current CDL edition. If we create a folder named _2015_ for this year edition and move all the code there, then all shares and links that we already provided on social networks will stop working. In this case we would need some kind of redirection to _cdl.rosedu.org/2015_.
But, for the moment I think it's okay if we just reorganize the past editions into separate folders and decide later for the current one.

**Comment by maria** [comment]
> For example, for the last year Etti edition, cdl-old.rosedu.org/2014-etti/, we could just create a folder named 2014-etti, move the code of that edition into the folder and everything should work properly. And so on, for the others editions.

It won't just work, we have to configure the site to know about it. This should be done in github.com/rosedu/sites_template first.

> However, the problem that we still need to face if we do so, is with the current CDL edition. If we create a folder named 2015 for this year edition and move all the code there, then all shares and links that we already provided on social networks will stop working. In this case we would need some kind of redirection to cdl.rosedu.org/2015.

Is not a real problem.

Let's just do this.
