### ISSUE TITLE
Find a cool motto

### ISSUE THREAD

**Issue by dinuand** [rosedu/cdl#2]
We need a nice, touchy, not so long motto for this year edition of CDL. 

![call_for_motto](https://cloud.githubusercontent.com/assets/6827645/6093251/2d54bc84-af07-11e4-9411-20a64c25bede.png)

**Comment by maria** [comment]
We can just use: `Super Hero Factory`

**Comment by dinuand** [comment]
If we say "Super Hero Factory", then we would still have an english first part of the website and we don't want that, as you said here [#3](https://github.com/rosedu/cdl/issues/3) .  @adasolcan , @calincru , what do you think? Can we find quickly a romanian motto? Or we could just say "Fabrica de super eroi".

**Comment by adasolcan** [comment]
"Fabrica de super eroi" doesn't sound very good.

**Comment by dinuand** [comment]
I made a joke, of course. @calincru says "Curs de dezvoltare libera", what do you think?

**Comment by adasolcan** [comment]
"Curs de dezvoltare libera" should be as a title, instead of "Community and Development Lab"

**Comment by dinuand** [comment]
Yea, we solved that problem, too. 
However, it seems pretty tricky to find a cool motto in romanian.

What do you think about this motto?

![logo-principal](https://cloud.githubusercontent.com/assets/6827645/6094472/ac204282-af33-11e4-98e9-7990c6de2b37.png)

**Comment by calincru** [comment]
LGTM, but without "v8.0".
