### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by maria** [rosedu/cdl#4]
1. Projects should be ordered alphabetically. Actually, anything should be. Projects names, Mentors name etc. 
   ![screenshot 2015-02-07 21 51 51](https://cloud.githubusercontent.com/assets/1681405/6093712/a0ab876a-af13-11e4-9d32-d0f98b9241b0.png)
2. The default image for projects shouldn't be "Coming soon", the project info is there, but it doesn't have a log. Find a default logo for a project. Like a GH fork icon ..

**Comment by dinuand** [comment]
I think this could work instead of the currently "Coming soon" default image.
So, we use this, @adasolcan , @calincru ?

![fork-a-repo](https://cloud.githubusercontent.com/assets/6827645/6093914/95f52e08-af1c-11e4-810b-4c9c004a265c.gif)

**Comment by dinuand** [comment]
I will take care of ordering information.

**Comment by adasolcan** [comment]
In the project description, if one field is missing, remove the whole field instead of leaving it blank.

**Comment by dinuand** [comment]
That, I think is kind of difficult to do. What we are doing now is to show for every project its components, defined in the _featured.yml_ file. It's like a pattern for every item. I don't now how exactly we could filter what to show and what to show not, depending on the project.  Take a look here[0] and here[1].
@maria , can you give us some advice?

[0]: [features.yml file](https://github.com/rosedu/cdl/blob/gh-pages/_data/features.yml)
[1]: [featured-item.html file](https://github.com/rosedu/cdl/blob/gh-pages/_includes/featured_item.html)
