### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by maria** [rosedu/cdl#5]
1. Diacritice. Peste tot. 

![screenshot 2015-02-07 21 55 56](https://cloud.githubusercontent.com/assets/1681405/6093725/26cab0aa-af14-11e4-802e-069074ea8c02.png)
1. Let's not use movie and fuzzy phrases :) Plain and simple. Maybe geeky :D.

![screenshot 2015-02-07 21 53 36](https://cloud.githubusercontent.com/assets/1681405/6093717/deb9d8b8-af13-11e4-8b0f-21ee1034afa4.png)
1. Writing the site name once more is not needed. Simple - "Apply" or "Register". They know we are talking about CDL.

**Comment by dinuand** [comment]
I can't find a spot where we didn't use diacritics, maybe you should be more specific. @adasolcan , you said something about the size of the text and also something about the words. Is something wrong with the words in the **About** section?
@calincru , everything seems ok to you?

**Comment by dinuand** [comment]
With a little help from @palcu, I think the text looks pretty nice now. 
What do you think? Is the background image and the text a better combination?

![problema](https://cloud.githubusercontent.com/assets/6827645/6094336/ad60a97a-af2e-11e4-8a1d-b1d7db767f8d.png)

**Comment by palcu** [comment]
Dude, I wasn't serious about it.

**Comment by dinuand** [comment]
After discussing with @adasolcan and @calincru , we decided the Apply section should look like this.
I will make the update in the next version of the website.

![inscrie-te](https://cloud.githubusercontent.com/assets/6827645/6096599/b1c33892-afa2-11e4-99e9-484ffa2b5de7.png)

**Comment by palcu** [comment]
:+1:
