### ISSUE TITLE
Photo banner

### ISSUE THREAD

**Issue by maria** [rosedu/cdl#6]
I think everyone is still in this [picture](https://www.dropbox.com/s/90eg9vcns6sd463/IMG_1005.JPG?dl=0) and is better.

**Comment by dinuand** [comment]
This is how it looks on the website. What do you think?

![picture_box](https://cloud.githubusercontent.com/assets/6827645/6094387/a9176fbe-af30-11e4-81e8-f9a05e95a70a.png)
